services:
  server:
    command: yarn start
    volumes:
      - $PWD:/usr/src/app
  proxy:
    ports:
      - "${SERVER_PORT}:80"
    environment:
      - SERVER_PORT=${SERVER_PORT}
  db:
    ports:
      - "5432:5432"