services:
  server:
    build: .
    depends_on:
      - db
  proxy:
    image: caddy:alpine
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
  adminer:
    image: adminer

volumes:
  caddy_data:
    external: true
  caddy_config: