services:
  server:
    build: .
    environment:
      SERVER_PORT: 3000
  proxy:
    image: caddy
    ports:
      - "3000:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: